# Generated by Django 2.2.3 on 2019-07-23 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nama_customer', models.CharField(max_length=100)),
                ('alamat_customer', models.CharField(max_length=100)),
                ('notlp_customer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
        migrations.CreateModel(
            name='jenis_brg',
            fields=[
                ('id_jenis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_jenis_brg',
            },
        ),
        migrations.CreateModel(
            name='merk_brg',
            fields=[
                ('id_merk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_merk', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_merk_brg',
            },
        ),
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('alamat_supplier', models.CharField(max_length=100)),
                ('notlp_supplier', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_supplier',
            },
        ),
        migrations.CreateModel(
            name='type_brg',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('nama_type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_type_brg',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nm_lengkap', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
                ('level', models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Admin', max_length=9)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='barang_masuk',
            fields=[
                ('id_brg_masuk', models.AutoField(primary_key=True, serialize=False)),
                ('kd_barang', models.CharField(max_length=10)),
                ('nm_barang', models.CharField(max_length=100)),
                ('tgl_masuk', models.DateField()),
                ('jml_masuk', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('no_resi', models.TextField()),
                ('foto_masuk', models.FileField(upload_to='foto/')),
                ('jenis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminhome.jenis_brg')),
                ('merk', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminhome.merk_brg')),
                ('tipe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adminhome.type_brg')),
            ],
            options={
                'db_table': 'tb_barang_masuk',
            },
        ),
        migrations.CreateModel(
            name='barang_keluar',
            fields=[
                ('id_brg_keluar', models.AutoField(primary_key=True, serialize=False)),
                ('tgl_keluar', models.DateField()),
                ('sn_barang', models.CharField(max_length=20)),
                ('jml_keluar', models.IntegerField()),
                ('alamat_customer', models.TextField()),
                ('no_bukti', models.CharField(max_length=20)),
                ('no_resi', models.CharField(max_length=20)),
                ('harga_satuan', models.IntegerField()),
                ('total_bayar', models.IntegerField()),
                ('foto_keluar', models.FileField(blank=True, upload_to='foto/')),
                ('kd_brg_keluar', models.CharField(max_length=10)),
                ('customer_id', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.customer')),
                ('jenis_id', models.ForeignKey(db_column='jenis_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.jenis_brg')),
                ('merk_id', models.ForeignKey(db_column='merk_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.merk_brg')),
                ('nama_barang', models.ForeignKey(db_column='nama_barang', on_delete=django.db.models.deletion.CASCADE, to='adminhome.barang_masuk')),
                ('tipe_id', models.ForeignKey(db_column='tipe_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.type_brg')),
            ],
            options={
                'db_table': 'tb_barang_keluar',
            },
        ),
    ]
