# Generated by Django 2.2.3 on 2019-07-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangkeluar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('serialnumber', models.CharField(max_length=20)),
                ('kode_barang', models.CharField(max_length=10)),
                ('no_bukti', models.CharField(max_length=20)),
                ('no_resi', models.CharField(blank=True, max_length=20)),
                ('jumlah', models.IntegerField()),
                ('harga_satuan', models.IntegerField()),
                ('total_bayar', models.IntegerField()),
                ('alamat_customer', models.TextField()),
                ('jenis_id', models.CharField(max_length=100)),
                ('merk_id', models.CharField(max_length=100)),
                ('tipe_id', models.CharField(max_length=100)),
                ('customer_id', models.CharField(max_length=100)),
                ('foto_keluar', models.ImageField(blank=True, null=True, upload_to='foto/')),
            ],
            options={
                'db_table': 'tb_barang_keluar',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('nama_customer', models.CharField(max_length=100)),
                ('alamat_customer', models.CharField(max_length=100)),
                ('notlp_customer', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_customer',
            },
        ),
        migrations.CreateModel(
            name='Jenis_brg',
            fields=[
                ('id_jenis', models.AutoField(primary_key=True, serialize=False)),
                ('nama_jenis', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_jenis_brg',
            },
        ),
        migrations.CreateModel(
            name='Merk_brg',
            fields=[
                ('id_merk', models.AutoField(primary_key=True, serialize=False)),
                ('nama_merk', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_merk_brg',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id_supplier', models.AutoField(primary_key=True, serialize=False)),
                ('nama_supplier', models.CharField(max_length=100)),
                ('alamat_supplier', models.CharField(max_length=100)),
                ('notlp_supplier', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_supplier',
            },
        ),
        migrations.CreateModel(
            name='Tipe_brg',
            fields=[
                ('id_tipe', models.AutoField(primary_key=True, serialize=False)),
                ('nama_tipe', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_tipe_brg',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nm_lengkap', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=8)),
                ('password', models.CharField(max_length=8)),
                ('level', models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Admin', max_length=9)),
            ],
            options={
                'db_table': 'tb_user',
            },
        ),
        migrations.CreateModel(
            name='Barang_masuk',
            fields=[
                ('id_brg_masuk', models.AutoField(primary_key=True, serialize=False)),
                ('kd_barang', models.CharField(max_length=10)),
                ('nm_barang', models.CharField(max_length=100)),
                ('sn_barang', models.CharField(max_length=20)),
                ('tgl_masuk', models.DateField()),
                ('jml_masuk', models.IntegerField()),
                ('harga_satuan', models.IntegerField()),
                ('no_resi', models.CharField(blank=True, max_length=100)),
                ('foto_masuk', models.ImageField(blank=True, upload_to='foto/')),
                ('jenis_id', models.ForeignKey(db_column='jenis_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Jenis_brg')),
                ('merk_id', models.ForeignKey(db_column='merk_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Merk_brg')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Supplier')),
                ('tipe_id', models.ForeignKey(db_column='tipe_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Tipe_brg')),
            ],
            options={
                'db_table': 'tb_barang_masuk',
            },
        ),
    ]
