# Generated by Django 2.2.4 on 2019-08-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='alamat_customer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='alamat_customer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='alamat_supplier',
            field=models.TextField(),
        ),
    ]
