# Generated by Django 2.2.3 on 2019-07-31 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barangkeluar',
            name='jenis_id',
        ),
        migrations.RemoveField(
            model_name='barangkeluar',
            name='merk_id',
        ),
        migrations.RemoveField(
            model_name='barangkeluar',
            name='tipe_id',
        ),
    ]
