# Generated by Django 2.2.3 on 2019-07-25 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='harga_satuan',
            field=models.CharField(blank=True, max_length=191),
        ),
    ]
