# Generated by Django 2.2.3 on 2019-07-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.FileField(upload_to='media/'),
        ),
    ]
