# Generated by Django 2.2.3 on 2019-07-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='no_resi',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
