# Generated by Django 2.2.3 on 2019-08-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stok_barang',
            name='sn_barang',
        ),
    ]
