# Generated by Django 2.2.3 on 2019-07-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_auto_20190730_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
