# Generated by Django 2.2.3 on 2019-07-24 07:40

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_auto_20190724_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='id_keluar',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
