# Generated by Django 2.2.3 on 2019-08-06 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_remove_stok_barang_sn_barang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok_barang',
            name='foto_stok',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='foto/'),
        ),
    ]
