# Generated by Django 2.2.3 on 2019-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_auto_20190811_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staf',
            field=models.BooleanField(default=False),
        ),
    ]
