# Generated by Django 2.2.4 on 2019-08-22 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_auto_20190820_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang_retur',
            fields=[
                ('id_brg_retur', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('no_bukti', models.CharField(max_length=100)),
                ('kd_barang', models.CharField(max_length=100)),
                ('nm_barang', models.CharField(max_length=100)),
                ('sn_barang', models.CharField(max_length=100)),
                ('keterangan', models.CharField(max_length=100)),
                ('customer_id', models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.Customer')),
                ('jenis_id', models.ForeignKey(db_column='jenis_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.Jenis_brg')),
                ('merk_id', models.ForeignKey(db_column='merk_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.Merk_brg')),
                ('supplier_id', models.ForeignKey(db_column='supplier_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.Supplier')),
                ('tipe_id', models.ForeignKey(db_column='tipe_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminhome.Tipe_brg')),
            ],
            options={
                'db_table': 'tb_brg_retur',
            },
        ),
    ]
