# Generated by Django 2.2.3 on 2019-07-23 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0002_auto_20190723_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.FileField(blank=True, upload_to='foto/'),
        ),
    ]
