# Generated by Django 2.2.3 on 2019-07-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_auto_20190724_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangkeluar',
            old_name='id_keluar',
            new_name='id',
        ),
    ]
