# Generated by Django 2.2.4 on 2019-08-22 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_barang_retur'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='barang_retur',
            table='tb_barang_retur',
        ),
    ]
