# Generated by Django 2.2.3 on 2019-08-06 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_auto_20190806_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='foto/'),
        ),
    ]
