# Generated by Django 2.2.3 on 2019-07-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_auto_20190723_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='jenis_id',
            field=models.ForeignKey(db_column='jenis_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Jenis_brg'),
        ),
        migrations.AlterField(
            model_name='barang_masuk',
            name='merk_id',
            field=models.ForeignKey(db_column='merk_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Merk_brg'),
        ),
        migrations.AlterField(
            model_name='barang_masuk',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Supplier'),
        ),
        migrations.AlterField(
            model_name='barang_masuk',
            name='tipe_id',
            field=models.ForeignKey(db_column='tipe_id', on_delete=django.db.models.deletion.CASCADE, to='adminhome.Tipe_brg'),
        ),
    ]
