# Generated by Django 2.2.3 on 2019-08-11 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0003_user_is_staf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_staf',
            field=models.BooleanField(default=True),
        ),
    ]
