# Generated by Django 2.2.4 on 2019-08-22 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_auto_20190822_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang_retur',
            name='is_deleted',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
