# Generated by Django 2.2.3 on 2019-07-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_auto_20190724_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
