# Generated by Django 2.2.3 on 2019-07-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_auto_20190723_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_keluar',
            name='foto_keluar',
            field=models.ImageField(upload_to='foto/'),
        ),
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.ImageField(blank=True, upload_to='foto/'),
        ),
    ]
