# Generated by Django 2.2.3 on 2019-08-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_auto_20190806_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
