# Generated by Django 2.2.3 on 2019-08-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0004_auto_20190811_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staf',
            new_name='is_staff',
        ),
    ]
