# Generated by Django 2.2.3 on 2019-07-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0005_auto_20190723_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Admin', max_length=10),
        ),
    ]
