# Generated by Django 2.2.3 on 2019-08-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0005_auto_20190806_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang_keluar',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barang_masuk',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jenis_brg',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='merk_brg',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tipe_brg',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
