# Generated by Django 2.2.3 on 2019-08-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0006_auto_20190806_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nama_customer',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jenis_brg',
            name='nama_jenis',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='merk_brg',
            name='nama_merk',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nama_supplier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notlp_supplier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tipe_brg',
            name='nama_tipe',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
