# Generated by Django 2.2.4 on 2019-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0006_auto_20190822_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang_retur',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
