# Generated by Django 2.2.3 on 2019-07-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0006_auto_20190724_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang_masuk',
            name='foto_masuk',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
