# Generated by Django 2.2.4 on 2019-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0007_barang_retur_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='barangkeluar',
            name='is_return',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
