# Generated by Django 2.2.3 on 2019-08-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhome', '0007_auto_20190807_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stok_barang',
            name='foto_stok',
            field=models.ImageField(blank=True, null=True, upload_to='foto/'),
        ),
    ]
